### ISSUE TITLE
Setup and configuring

### ISSUE THREAD

**Issue by mrrcomp** [php-mqtt/client-examples#1]
Hi

I am attempting to integrate this with my website. but I keep getting errors on the require . I can see the files listed in c:\users\Administrator\Vendor

So I tried ..

require     'C:/users/Administrator/vendor/autoload.php';
require __DIR__ . '/SimpleLogger.php';

use PhpMqtt\Client\src\Exceptions\ConnectingToBrokerFailedException;
use PhpMqtt\Client\src\Exceptions\DataTransferException;
use PhpMqtt\Client\src\Exceptions\UnexpectedAcknowledgementException;

I also attempted to copy the mentioned files directly to my website folders also get errors..

Is there a tutorial of how to install and configure???

Regards

Meir

**Comment by Namoshek** [comment]
There is currently no detailed tutorial on how to run the examples, since the process follows the common development process of PHP with composer as package manager. I must admit that I focus my PHP development on Linux, so it might be slightly different on Windows. But basically, the steps to run the example are as follows:

1. Open a shell to the directory where you store your projects and where a new directory will be created for the examples.
2. Clone the git repository to a new folder `client-examples`:
    ```sh
    git clone https://github.com/php-mqtt/client-examples.git
    ```
3. Change the directory and install composer dependencies:
    ```sh
    cd client-examples
    composer install
    ```
4. Change the `$server` and `$port` variables in `subscribe.php` and `publish.php` according to your needs. To test the client, you can for example use the [HiveMQ Test Broker](https://www.hivemq.com/public-mqtt-broker/).
5. Run the examples. If you want to subscribe to the messages published by the other script, you need to run the following commands in this order in two different shells:
    ```sh
    php subscribe.php
    ```
    ```sh
    php publish.php
    ```

**Comment by mrrcomp** [comment]
@Namoshek ..Thanks for your swift response

I followed your instructions but there is composer in the client-exampls directory or any of its sub directories???


Regards

**Comment by Namoshek** [comment]
Install it from https://getcomposer.org

**Comment by Namoshek** [comment]
I guess this issue is resolved by now. If not, feel free to ask more questions and I'll reopen it.
